
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20150930 (SVN rev 66)
//----------------------------------------------------

package analizadores;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int CADENA = 14;
  public static final int COMA = 9;
  public static final int R_REGISTROS = 3;
  public static final int ENTER = 8;
  public static final int NUMERICO = 15;
  public static final int EOF = 0;
  public static final int CORCHETEABRE = 4;
  public static final int COMENTARIOU = 12;
  public static final int LLAVEABRE = 10;
  public static final int IGUAL = 6;
  public static final int error = 1;
  public static final int SPACE = 7;
  public static final int R_CLAVES = 2;
  public static final int CORCHETECIERRA = 5;
  public static final int COMENTARIOM = 13;
  public static final int LLAVECIERRA = 11;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "R_CLAVES",
  "R_REGISTROS",
  "CORCHETEABRE",
  "CORCHETECIERRA",
  "IGUAL",
  "SPACE",
  "ENTER",
  "COMA",
  "LLAVEABRE",
  "LLAVECIERRA",
  "COMENTARIOU",
  "COMENTARIOM",
  "CADENA",
  "NUMERICO"
  };
}

