
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20150930 (SVN rev 66)
//----------------------------------------------------

package analizadoresRep;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int R_PROMEDIO = 7;
  public static final int R_IMPRIMIR = 11;
  public static final int R_CONTARSI = 8;
  public static final int CADENA = 25;
  public static final int R_SUMAR = 5;
  public static final int IGUAL = 14;
  public static final int R_GRAFICAR = 12;
  public static final int R_NUMERICO = 4;
  public static final int MAYORQUE = 18;
  public static final int ID = 27;
  public static final int ENTER = 22;
  public static final int SPACE = 21;
  public static final int COMENTARIOU = 23;
  public static final int COMA = 13;
  public static final int PARENTESISABRE = 15;
  public static final int EOF = 0;
  public static final int R_CONTAR = 6;
  public static final int MENORQUE = 19;
  public static final int R_ARCHIVO = 2;
  public static final int R_OBTENERSI = 10;
  public static final int COMENTARIOM = 24;
  public static final int NOIGUAL = 20;
  public static final int NUMERO = 26;
  public static final int error = 1;
  public static final int PUNTOCOMA = 17;
  public static final int PARENTESISCIERRA = 16;
  public static final int R_CADENA = 9;
  public static final int R_LEERARCHIVO = 3;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "R_ARCHIVO",
  "R_LEERARCHIVO",
  "R_NUMERICO",
  "R_SUMAR",
  "R_CONTAR",
  "R_PROMEDIO",
  "R_CONTARSI",
  "R_CADENA",
  "R_OBTENERSI",
  "R_IMPRIMIR",
  "R_GRAFICAR",
  "COMA",
  "IGUAL",
  "PARENTESISABRE",
  "PARENTESISCIERRA",
  "PUNTOCOMA",
  "MAYORQUE",
  "MENORQUE",
  "NOIGUAL",
  "SPACE",
  "ENTER",
  "COMENTARIOU",
  "COMENTARIOM",
  "CADENA",
  "NUMERO",
  "ID"
  };
}

